Ready for engineers to add reference docs
phylaxsystems/phylax-std pull request #20
Opened 2024-07-03 00:54 UTC by staringispolite

<img width="1441" alt="image" src="https://github.com/phylaxsystems/phylax-std/assets/151620/41aea058-52b0-40f5-abcd-944a377ae469">

Now whenever the docs github action runs, it'll pull down docs from this repo and into the sidebar section on the lower left of this screenshot (the "Phylax Standard Library" label and everything under it is defined in this repo and dropped in to the site) 

There's a group for reference docs, with a sample page people can copy if they like. There's also an introduction page with some pointers, as an example of top-level pages you can add

2024-07-03 00:58 UTC, staringispolite commented
@odyslam any idea why tests would be failing? (were they always? didn't look like there's anything when I tried to rebase)

2024-07-05 17:40 UTC, odyslam commented on docs/introduction.mdx
> +title: Introduction to Phylax STL
The name of the library is `phylax-std`

2024-07-05 17:41 UTC, odyslam requested changes
fix the name of the library

2024-07-05 20:58 UTC, staringispolite commented
ah my fingers must have done that because of C++ STL

can I change the menu item to say “Phylax Standard Library” like
foundry-rs/forge-std does? (STD means “sexually transmitted disease” in
english so it feels odd for a header)

On Fri, Jul 5, 2024 at 10:41 AM odysseas.eth ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> fix the name of the library
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/phylaxsystems/phylax-std/pull/20#pullrequestreview-2161073632>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABFARBJPNALJQMDOBNUWY3ZK3LEDAVCNFSM6AAAAABKIRJO22VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNRRGA3TGNRTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-06 02:56 UTC, staringispolite commented
@odyslam updated to Phylax Standard Library, how's that?

(this is just a placeholder btw, so that engineers have an example of how pages work)

2024-10-01 21:39 UTC, czepluch commented
I think we can close this PR.

2024-10-15 14:58 UTC, closed without merging